language: ruby
before_install:
  - gem install rake
  - gem install puppetlabs_spec_helper
  - gem install rspec
  - gem install puppet-lint

notifications:
  email:
    - thomas.foster80@gmail.com
rvm:
  - 2.1.1 
  - 1.9.3 
env:
  - PUPPET_VERSION=3.2.3
  - PUPPET_VERSION=3.2.2
  - PUPPET_VERSION=2.7.25
script:
  - bundle exec rspec
