name    'nohtyp-rhnreg_ks'
version '0.0.1'
source 'git://github.com/nohtyp/rhnreg_ks.git'
author 'nohtyp'
license 'Apache License, Version 2.0'
dependency 'adrien/boolean', '>=0.9.0'
summary 'rhnreg_ks provider for Puppet'
project_page 'https://github.com/nohtyp/rhnreg_ks.git'
description 'This module provides Custom Providers for Red Hat Network Registering.
             and takes care of registering system during VMware cloning'
